#ifndef LIBRARY_H
#define LIBRARY_H

#define LIBRARY_VERSION_MAJOR 0
#define LIBRARY_VERSION_MINOR 0
#define LIBRARY_VERSION_PATCH 1
#define LIBRARY_VERSION "0.0.1"

#ifndef LIBAPI
    #define LIBAPI static
#endif // LIBAPI

#ifdef LIBRARY_IMPLEMENTATION

#endif // LIBRARY_IMPLEMENTATION

#endif // LIBRARY_H

